name: Xcodebuild Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          xcode-version: '13.4.1'
        uses: sersoft-gmbh/xcodebuild-action@v2.0
          with:
            project: /EssentialFeed/EssentialFeed.xcodeproj
            scheme: CI
            destination: platform=macOS
            action: test
