name: Xcodebuild Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-12.3

    steps:
      - uses: actions/checkout@v3
      - name: Xcodebuild Action
        uses: sersoft-gmbh/xcodebuild-action@v2.0
        with:
          project: ./EssentialFeed.xcodeproj
          scheme: CI
          destination: platform=macOS
          action: test
